### ISSUE TITLE
代码和数据集

### ISSUE THREAD

**Issue by swjtulinxi** [lironui/MACU-Net#1]
请问代码和数据集什么时候发布啊。可不可以先把数据集发布了

**Comment by lironui** [comment]
数据集你搜论文里引用的文献，有下载链接的

**Comment by swjtulinxi** [comment]
你好，请问GID数据集你们选的哪些图像啊，没看到编号啊

**Comment by lironui** [comment]
我们会在论文接收后发布代码和编号，感谢对我们工作的关注。

**Comment by swjtulinxi** [comment]
你们的论文不是已经接受了吗？？  还有请问GID数据集不是有5类+一个others吗，请问你们在计算loss和精度时 是忽略了others还是没有啊，也就是算5类还是6类呢，因为打算复现一下

**Comment by lironui** [comment]
还在审稿中，arXiv张贴并不是接收。用了6类计算精度。
